/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CriteriaAttributeType = "benefit" | "cost";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Alternatives {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  project_id: number;
  updated_at: Generated<Timestamp>;
}

export interface AlternativeValue {
  alternative_id: number;
  created_at: Generated<Timestamp>;
  crips_id: number;
  criteria_id: number;
  id: Generated<number>;
  numerical_value: Numeric;
  updated_at: Generated<Timestamp>;
}

export interface Crips {
  created_at: Generated<Timestamp>;
  criteria_id: number;
  id: Generated<number>;
  label: string;
  updated_at: Generated<Timestamp>;
  value: number;
}

export interface Criteria {
  attribute_type: CriteriaAttributeType;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  project_id: number;
  updated_at: Generated<Timestamp>;
  weight: Numeric;
}

export interface Projects {
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<number>;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string;
  password: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  alternative_value: AlternativeValue;
  alternatives: Alternatives;
  crips: Crips;
  criteria: Criteria;
  projects: Projects;
  users: Users;
}
